# Site settings
title: Milena Bekerle Unternehmensberatung
subtitle: Human Resource Development
email: milena@bekerle.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Schiessstattgasse 73
city: Graz
state: 
zip_code: 8010
country: Austria
phone: +43 664 85 83 967

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/mag-ª-milena-bekerle/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
