# Site settings
title: Milena Bekerle Unternehmensberatung
subtitle: Human Resource Development
email: milena@bekerle.com
description: IHRE ANSPRECHPARTNERIN FÜR IHRE PERSONALTHEMEN
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Milena Bekerle
street_address: Schiessstattgasse 73
city: Graz
state: 
zip_code: 8010
country: Austria
phone: +43 664 85 83 967

# Social settings
500px_url:
facebook_url:
github_url:
xing_url: https://www.xing.com/profile/Milena_Bekerle/cv
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/mag-ª-milena-bekerle/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
